### PR TITLE
Update expiration value

### PR DESCRIPTION
**Pull request by priyanshu92**
This removes the duplicate expiration value.

- Removes the duplicate expiration value and uses the value of already defined embeddedExpiration.

Resolves aspnet/home#2847

### CODE REVIEW

**Comment by muratg** [comment]
Thanks @priyanshu92!  @natemcmaster, let's review and merge at a suitable time. Thanks.

**Comment by davidfowl** [comment]
Looks correct to me. 

/cc @natemcmaster @blowdart

**Comment by natemcmaster** [comment]
Thanks @priyanshu92

**Comment by priyanshu92** [comment]
Happy to contribute 😄

**Pull request merged**
