### PR TITLE
KeyDerivation.Pbkdf2 use with byte[]

### PR DESCRIPTION
**Pull request by bwolkerstorfer**
change addresses #87 
- changed interfaces and providers PBKDF2 to support byte[] as input for password
- added tests for new logic

### CODE REVIEW

**Comment by muratg** [comment]
cc @blowdart

**Comment by blowdart** [comment]
We go to extraordinary lengths to pin memory, clear memory when we're done using it, etc. This PR deletes all of that work, and has a huge risk that passwords and byte arrays representing passwords hang around in memory long after they should have been cleared.

A further attack vector added with Encoding.UTF8.GetBytes(password). 

This PR is unsafe and must be rejected.

**Comment by PinpointTownes** [comment]
@blowdart I have no particular interest for this new API signature, but I'd really appreciate if you could detail your reasoning (not everyone is a security expert :trollface:).

> We go to extraordinary lengths to pin memory, clear memory when we're done using it, etc. This PR deletes all of that work, and has a huge risk that passwords and byte arrays representing passwords hang around in memory long after they should have been cleared.

Since the password is initially flowed as a string, isn't that futile anyway? No matter what you do to reduce the lifetime of the intermediate byte arrays, the password is still held in clear as a string until it's garbage-collected. I'm not sure to understand how this PR makes this situation worse.

> A further attack vector added with Encoding.UTF8.GetBytes(password).

Aren't all the PBKDF2 providers (managed, Win7/Win8) already using it? AFAICT, only the data protection extensions use a UTF-8 encoding that throws on invalid byte sequences (if that's what you mean)
  - https://github.com/aspnet/DataProtection/blob/dev/src/Microsoft.AspNetCore.Cryptography.KeyDerivation/PBKDF2/ManagedPbkdf2Provider.cs#L71
  - https://github.com/aspnet/DataProtection/blob/dev/src/Microsoft.AspNetCore.Cryptography.KeyDerivation/PBKDF2/Win7Pbkdf2Provider.cs#L53
  - https://github.com/aspnet/DataProtection/blob/dev/src/Microsoft.AspNetCore.Cryptography.KeyDerivation/PBKDF2/Win8Pbkdf2Provider.cs#L86

**Comment by blowdart** [comment]
We are pinning and clearing what we produced after we've done it. It's a best effort here, and surely you agree we ought to make an effort rather than ignoring it altogether.

**Comment by PinpointTownes** [comment]
> It's a best effort here, and surely you agree we ought to make an effort rather than ignoring it altogether.

Sure (you could even use `SecureString` instead of a plain old `string`).

My question was: why do you think this PR is bad from a security perspective?

**Comment by blowdart** [comment]
You know how I feel about securestring you troll :p

Removing the pinning and clearing of the array which we converted the string into means we now have a second copy of the the plaintext password floating about, which is obviously a bad idea.

**Comment by PinpointTownes** [comment]
> You know how I feel about securestring you troll :p

Me, trolling? Nah (tho I've always wondered why you hated `SecureString` so much) :smile:

Actually, the DP stack heavily uses `Secret` - which seems to be an equivalent of `SecureString` that also relies on `CryptProtectMemory` - to "protect" critical things like DP master keys.

IMHO, user passwords are at least as sensitive as master keys, so it wouldn't surprise me if the PBKDF helpers accepted an `ISecret`/`SecureString`.

> Removing the pinning and clearing of the array which we converted the string into means we now have a second copy of the the plaintext password floating about, which is obviously a bad idea.

Sure, [this line](https://github.com/aspnet/DataProtection/pull/168/files#diff-a950609e3baa0d3f5d89e816dce57e0dR35) could be updated to use pinning and clear the intermediate bytes buffer before returning, but it's not clear to me why this makes the PR totally "unsafe".

Anyway, thanks for the details :smile:

**Pull request closed without merging**
