### PR TITLE
Add script to add AutoGenKeys section and UCL for it

### PR DESCRIPTION
**Pull request by pakrym**
Based on https://support.microsoft.com/en-us/kb/2915218

Usage `.\Provision-AutoGenKeys.ps1 DefaultAppPool`
@muratg @blowdart @Eilon

### CODE REVIEW

**Comment by blowdart** [comment]
Feel free to merge this, or talk to @HaoK if you're feeling nervous. Hao this doesn't need to become part of a package or anything, but it does need to live in the repo.

**Comment by davidfowl** [comment]
@blowdart Is this a short term solution? This relies on full .NET and ASP.NET 4.x being enabled right?

**Comment by pakrym** [comment]
@davidfowl  No, it should create keys and set acl for them.

**Comment by blowdart** [comment]
It's a short term fix for #102 - but it doesn't rely on anything. We just need to ensure people run this manually, which sucks. For RC2 we need a much better solution where the registry keys are created automatically.

**Comment by davidfowl** [comment]
How does this work https://github.com/aspnet/DataProtection/pull/106/files#diff-5458ff3cb68d9ae62ebd612f39237b5bR38? Doesn't it rely on the ASP.NET base key being created?

**Comment by pakrym** [comment]
True,  will add a check for upper levels

**Comment by blowdart** [comment]
Ah yea, just creating it blindly should be fine. Should still have that name, for .net 4 & 5 cookie sharing

**Comment by blowdart** [comment]
Also does WOW64 get in the way here? Need to test for both 32 and 64 bit

**Comment by GrabYourPitchforks** [comment]
@davidfowl WAS creates that registry key automatically when creating an app pool which is marked as "CLR v4.x".

**Comment by Eilon** [comment]
Looks a'ight to me, as best I can tell.

@anurse to review the PS code because it's PS code and he knows PS code and I don't know PS code :smile:

**Comment by pakrym** [comment]
I updated script to check for asp.net folder

**Comment by anurse** [comment]
Yep, it looks like PS code to me :). :shipit: from that perspective alone

**Comment by davidfowl** [comment]
@GrabYourPitchforks the concern is that .NET Framework isn't always available. I just want to make sure that if we're relying on it, it's a short term solution.

**Comment by pakrym** [comment]
@davidfowl the only thing is, this script requires .net 4 and PS 3

**Comment by muratg** [comment]
Yes, this has to be a short term solution.  @pakrym is assigned to #102 for the correct fix in RC2.

**Comment by GrabYourPitchforks** [comment]
That registry key was only ever intended to be used in the Helios hosting case. You'd obviously need to move off of it now that Helios has been eliminated as a hosting option.

**Comment by poke** [comment]
I just ran into the issue that I was trying to run this on a machine that didn’t have PowerShell 3, so I ported the script into an actual executable. So in case anyone else needs this: https://github.com/poke/aspnet-ProvisionAutoGenKeys

**Pull request merged**
